export enum CommunityRole {
  COMMUNITY_MEMBER = 1,
  COMMUNITY_ADMIN
}

export enum CommunityStatus {
  ACTIVE_MEMBER = 1,
  INACTIVE_MEMBER
}

export enum Emoji {
  SPARKLING_HEART = 'SPARKLING_HEART',
  RAISING_HANDS = 'RAISING_HANDS',
  ROCKET = 'ROCKET',
  THINKING = 'THINKING',
  FOLDING_HANDS = 'FOLDING_HANDS',
}
